src/main/java/com/jspxcms/core/domain/Attachment.java
package com.jspxcms.core.domain;

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.jspxcms.common.file.FilesEx;
import com.jspxcms.core.support.Siteable;

/**
 * Attachment
 * 
 * @author liufang
 * 
 */
@Entity
@Table(name = "cms_attachment")
public class Attachment implements Siteable, java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Transient
	public boolean isUsed() {
		Set<AttachmentRef> refs = getRefs();
		return refs != null && !refs.isEmpty();
	}

	@Transient
	public String getSize() {
		Long length = getLength();
		return FilesEx.getSize(length);
	}

	@Transient
	public void applyDefaultValue() {
		if (getIp() == null) {
			setIp("localhost");
		}
		if (getTime() == null) {
			setTime(new Timestamp(System.currentTimeMillis()));
		}
	}

	private Integer id;
	private Set<AttachmentRef> refs = new HashSet<AttachmentRef>(0);

	private Site site;
	private User user;

	private String name;
	private String ip;
	private Date time;
	private Long length;

	@Id
	@Column(name = "f_attachment_id", unique = true, nullable = false)
	@TableGenerator(name = "tg_cms_attachment", pkColumnValue = "cms_attachment", initialValue = 1, allocationSize = 10)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "tg_cms_attachment")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = { CascadeType.REMOVE }, mappedBy = "attachment")
	public Set<AttachmentRef> getRefs() {
		return this.refs;
	}

	public void setRefs(Set<AttachmentRef> refs) {
		this.refs = refs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_site_id", nullable = false)
	public Site getSite() {
		return site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_user_id", nullable = false)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "f_name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "f_ip", length = 100)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "f_time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "f_length")
	public Long getLength() {
		return this.length;
	}

	public void setLength(Long length) {
		this.length = length;
	}

}

src/main/java/com/jspxcms/core/domain/AttachmentRef.java
package com.jspxcms.core.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;

/**
 * AttachmentRef
 * 
 * @author liufang
 * 
 */
@Entity
@Table(name = "cms_attachment_ref")
public class AttachmentRef implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Transient
	public void applyDefaultValue() {
		if (getSite() == null) {
			if (getAttachment() != null) {
				setSite(getAttachment().getSite());
			}
		}
	}

	private Integer id;
	private Attachment attachment;
	private Site site;

	private String ftype;
	private Integer fid;

	@Id
	@Column(name = "f_attachementref_id", unique = true, nullable = false)
	@TableGenerator(name = "tg_cms_attachment_ref", pkColumnValue = "cms_attachment_ref", initialValue = 1, allocationSize = 10)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "tg_cms_attachment_ref")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_site_id", nullable = false)
	public Site getSite() {
		return site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_attachment_id", nullable = false)
	public Attachment getAttachment() {
		return this.attachment;
	}

	public void setAttachment(Attachment attachment) {
		this.attachment = attachment;
	}

	@Column(name = "f_ftype", nullable = false, length = 100)
	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	@Column(name = "f_fid", nullable = false)
	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

}

src/main/java/com/jspxcms/core/domain/Attribute.java
package com.jspxcms.core.domain;

import com.google.common.base.Objects;
import com.jspxcms.core.support.Siteable;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Attribute
 *
 * @author liufang
 */
@Entity
@Table(name = "cms_attribute")
public class Attribute implements Siteable, java.io.Serializable {
    private static final long serialVersionUID = 1L;

    @Transient
    public void applyDefaultValue() {
        if (getSeq() == null) {
            setSeq(Integer.MAX_VALUE);
        }
        if (getScale() == null) {
            setScale(false);
        }
        if (getExact() == null) {
            setExact(false);
        }
        if (getWatermark() == null) {
            setWatermark(false);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Attribute)) {
            return false;
        }
        Attribute that = (Attribute) o;
        return Objects.equal(id, that.id);
    }

    private Integer id;

    private Site site;

    private String number;
    private String name;
    private Integer seq;
    private Boolean withImage;
    private Boolean scale;
    private Boolean exact;
    private Boolean watermark;
    private Integer imageWidth;
    private Integer imageHeight;

    @XmlTransient
    @Id
    @Column(name = "f_attribute_id", unique = true, nullable = false)
    @TableGenerator(name = "tg_cms_attribute", pkColumnValue = "cms_attribute", initialValue = 1, allocationSize = 10)
    @GeneratedValue(strategy = GenerationType.TABLE, generator = "tg_cms_attribute")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @XmlTransient
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "f_site_id", nullable = false)
    public Site getSite() {
        return this.site;
    }

    public void setSite(Site site) {
        this.site = site;
    }

    @Column(name = "f_number", nullable = false, length = 20)
    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    @Column(name = "f_name", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "f_seq", nullable = false)
    public Integer getSeq() {
        return this.seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    @Column(name = "f_is_with_image", nullable = false, length = 1)
    public Boolean getWithImage() {
        return this.withImage;
    }

    public void setWithImage(Boolean withImage) {
        this.withImage = withImage;
    }

    @Column(name = "f_is_scale", nullable = false, length = 1)
    public Boolean getScale() {
        return scale;
    }

    public void setScale(Boolean scale) {
        this.scale = scale;
    }

    @Column(name = "f_is_exact", nullable = false, length = 1)
    public Boolean getExact() {
        return exact;
    }

    public void setExact(Boolean exact) {
        this.exact = exact;
    }

    @Column(name = "f_is_watermark", nullable = false, length = 1)
    public Boolean getWatermark() {
        return watermark;
    }

    public void setWatermark(Boolean watermark) {
        this.watermark = watermark;
    }

    @Column(name = "f_image_width")
    public Integer getImageWidth() {
        return this.imageWidth;
    }

    public void setImageWidth(Integer imageWidth) {
        this.imageWidth = imageWidth;
    }

    @Column(name = "f_image_height")
    public Integer getImageHeight() {
        return this.imageHeight;
    }

    public void setImageHeight(Integer imageHeight) {
        this.imageHeight = imageHeight;
    }

}

src/main/java/com/jspxcms/core/domain/Comment.java
package com.jspxcms.core.domain;

import java.sql.Timestamp;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.jspxcms.common.web.Anchor;
import com.jspxcms.core.support.Siteable;

/**
 * Comment评论对象
 * 
 * @author liufang
 * 
 */
@Entity
@Table(name = "cms_comment")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "f_ftype", discriminatorType = DiscriminatorType.STRING)
public abstract class Comment implements Siteable, java.io.Serializable {
	private static final long serialVersionUID = 1L;
	/**
	 * 未审核
	 */
	public static final int SAVED = 0;
	/**
	 * 已审核
	 */
	public static final int AUDITED = 1;
	/**
	 * 推荐
	 */
	public static final int RECOMMEND = 2;
	/**
	 * 屏蔽
	 */
	public static final int DISABLED = 3;
	/**
	 * Digg标记
	 */
	public static final String LIKE_MARK = "CommentLike";

	@Transient
	public abstract Anchor getAnchor();

	/**
	 * 获取所有父节点。最上层的排在最前面。
	 * 
	 * @return
	 */
	@Transient
	public List<Comment> getParents() {
		LinkedList<Comment> parents = new LinkedList<Comment>();
		Comment p = getParent();
		while (p != null) {
			parents.addLast(p);
			p = p.getParent();
		}
		return parents;
	}

	public void applyDefaultValue() {
		if (getCreationDate() == null) {
			setCreationDate(new Timestamp(System.currentTimeMillis()));
		}
		if (getScore() == null) {
			setScore(0);
		}
		if (getStatus() == null) {
			setStatus(SAVED);
		}
	}

	private Integer id;

	private Site site;
	private User creator;
	private User auditor;
	private Comment parent;

	private String ftype;
	private Integer fid;
	private Date creationDate;
	private Date auditDate;
	private String ip;
	private String country;
	private String area;
	private Integer score;
	private Integer status;
	private String text;

	@Id
	@Column(name = "f_comment_id", unique = true, nullable = false)
	@TableGenerator(name = "tg_cms_comment", pkColumnValue = "cms_comment", initialValue = 1, allocationSize = 10)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "tg_cms_comment")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_creator_id", nullable = false)
	public User getCreator() {
		return this.creator;
	}

	public void setCreator(User creator) {
		this.creator = creator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_auditor_id", nullable = false)
	public User getAuditor() {
		return this.auditor;
	}

	public void setAuditor(User auditor) {
		this.auditor = auditor;
	}

	// NotFoundAction.IGNORE为了防止父评论被删除导致的错误
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_parent_id", nullable = true)
	@NotFound(action = NotFoundAction.IGNORE)
	public Comment getParent() {
		return parent;
	}

	public void setParent(Comment parent) {
		this.parent = parent;
	}

	@Column(name = "f_ftype", nullable = false, length = 50, insertable = false, updatable = false)
	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

	@Column(name = "f_fid", nullable = false)
	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "f_creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "f_audit_date", length = 19)
	public Date getAuditDate() {
		return this.auditDate;
	}

	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

	@Column(name = "f_score", nullable = false)
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "f_ip", nullable = true, length = 100)
	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "f_country", length = 100)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "f_area", length = 100)
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "f_status", nullable = false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "f_text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}

src/main/java/com/jspxcms/core/domain/InfoComment.java
package com.jspxcms.core.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

import com.jspxcms.common.web.Anchor;

/**
 * InfoComment
 * 
 * @author liufang
 * 
 */
@Entity
@DiscriminatorValue("Info")
public class InfoComment extends Comment {
	private static final long serialVersionUID = 1L;

	@Override
	@Transient
	public Anchor getAnchor() {
		return info;
	}

	private Info info;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_fid", nullable = false, insertable = false, updatable = false)
	public Info getInfo() {
		return info;
	}

	public void setInfo(Info info) {
		this.info = info;
	}
}

src/main/java/com/jspxcms/core/domain/InfoProcess.java
package com.jspxcms.core.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

/**
 * InfoComment
 * 
 * @author liufang
 * 
 */
@Entity
@DiscriminatorValue("1")
public class InfoProcess extends WorkflowProcess {
	private static final long serialVersionUID = 1L;

	@Override
	@Transient
	public String getName() {
		return getInfo().getTitle();
	}

	private Info info;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_data_id", nullable = false, insertable = false, updatable = false)
	public Info getInfo() {
		return info;
	}

	public void setInfo(Info info) {
		this.info = info;
	}
}

src/main/webapp/WEB-INF/views/core/message/message_list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="fnx" uri="http://java.sun.com/jsp/jstl/functionsx"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="f" uri="http://www.jspxcms.com/tags/form"%>
<%@ taglib prefix="shiro" uri="http://shiro.apache.org/tags"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<!DOCTYPE html>
<html>
<head>
<jsp:include page="/WEB-INF/views/head.jsp"/>
<script type="text/javascript">
$(function() {
	$("#sortHead").headSort();
	<shiro:hasPermission name="core:message:edit">
	$("#pagedTable tbody tr").dblclick(function(eventObj) {
		var nodeName = eventObj.target.nodeName.toLowerCase();
		if(nodeName!="input"&&nodeName!="select"&&nodeName!="textarea") {
			location.href=$("#edit_opt_"+$(this).attr("beanid")).attr('href');
		}
	});
	</shiro:hasPermission>
});
function confirmDelete() {
	return confirm("<s:message code='confirmDelete'/>");
}
function optSingle(opt) {
	if(Cms.checkeds("ids")==0) {
		alert("<s:message code='pleaseSelectRecord'/>");
		return false;
	}
	if(Cms.checkeds("ids")>1) {
		alert("<s:message code='pleaseSelectOne'/>");
		return false;
	}
	var id = $("input[name='ids']:checkbox:checked").val();
	location.href=$(opt+id).attr("href");
}
function optMulti(form, action, msg) {
	if(Cms.checkeds("ids")==0) {
		alert("<s:message code='pleaseSelectRecord'/>");
		return false;
	}
	if(msg && !confirm(msg)) {
		return false;
	}
	form.action=action;
	form.submit();
	return true;
}
function optDelete(form) {
	if(Cms.checkeds("ids")==0) {
		alert("<s:message code='pleaseSelectRecord'/>");
		return false;
	}
	if(!confirmDelete()) {
		return false;
	}
	form.action='delete.do';
	form.submit();
	return true;
}
</script>
</head>
<body class="skin-blue content-body">
<jsp:include page="/WEB-INF/views/commons/show_message.jsp"/>
<div class="content-header">
	<h1><s:message code="message.management"/> - <s:message code="list"/> <small>(<s:message code="totalElements" arguments="${pagedList.totalElements}"/>)</small></h1>
</div>
<div class="content">
	<div class="box box-primary">
		<div class="box-body table-responsive">
			<form class="form-inline ls-search" action="list.do" method="get">
				<div class="form-group">
				  <label><s:message code="message.subject"/></label>
			  	<input class="form-control input-sm" type="text" name="search_CONTAIN_messageText.subject" value="${requestScope['search_CONTAIN_messageText.subject'][0]}" style="width:150px;"/>
				</div>
				<div class="form-group">
				  <label><s:message code="message.text"/></label>
			  	<input class="form-control input-sm" type="text" name="search_CONTAIN_messageText.text" value="${requestScope['search_CONTAIN_messageText.text'][0]}" style="width:150px;"/>
				</div>
				<div class="form-group">
				  <label><s:message code="message.sender"/></label>
			  	<input class="form-control input-sm" type="text" name="search_LIKE_sender.username" value="${requestScope['search_LIKE_sender.username'][0]}" style="width:120px;"/>
				</div>
				<div class="form-group">
				  <label><s:message code="message.receiver"/></label>
			  	<input class="form-control input-sm" type="text" name="search_LIKE_receiver.username" value="${requestScope['search_LIKE_receiver.username'][0]}" style="width:120px;"/>
				</div>
				<div class="form-group">
				  <label><s:message code="beginTime"/></label>
			  	<f:text class="form-control input-sm" name="search_GTE_sendTime_Timestamp" value="${search_GTE_sendTime_Timestamp[0]}" onclick="WdatePicker({dateFmt:'yyyy-MM-ddTHH:mm:ss'});" style="width:150px;"/>
				</div>
				<div class="form-group">
				  <label><s:message code="endTime"/></label>
			  	<f:text class="form-control input-sm" name="search_LTE_sendTime_Timestamp" value="${search_LTE_sendTime_Timestamp[0]}" onclick="WdatePicker({dateFmt:'yyyy-MM-ddTHH:mm:ss'});" style="width:150px;"/>
				</div>
				<div class="form-group">
				  <label><s:message code="message.deletionFlag"/></label>
			  	<select class="form-control input-sm" name="search_EQ_deletionFlag">
			  		<option value=""><s:message code="allSelect"/></option>
			  		<option value="0"<c:if test="${'0' eq search_EQ_deletionFlag[0]}"> selected="selected"</c:if>><s:message code="message.deletionFlag.0"/></option>
			  		<option value="1"<c:if test="${'1' eq search_EQ_deletionFlag[0]}"> selected="selected"</c:if>><s:message code="message.deletionFlag.1"/></option>
			  		<option value="2"<c:if test="${'2' eq search_EQ_deletionFlag[0]}"> selected="selected"</c:if>><s:message code="message.deletionFlag.2"/></option>
		  		</select>
				</div>
				<div class="form-group">
				  <label><s:message code="message.unread"/></label>
			  	<select class="form-control input-sm" name="search_EQ_unread_Boolean">
			  		<option value=""><s:message code="allSelect"/></option>
			  		<option value="true"<c:if test="${'true' eq search_EQ_unread_Boolean[0]}"> selected="selected"</c:if>><s:message code="message.unread.1"/></option>
			  		<option value="false"<c:if test="${'false' eq search_EQ_unread_Boolean[0]}"> selected="selected"</c:if>><s:message code="message.unread.0"/></option>
		  		</select>
				</div>
			  <button class="btn btn-default btn-sm" type="submit"><s:message code="search"/></button>
			</form>
			<form method="post">
				<tags:search_params/>
				<div class="btn-toolbar ls-btn-bar">
					<div class="btn-group">
						<shiro:hasPermission name="core:message:edit">
						<button class="btn btn-default" type="button" onclick="return optSingle('#edit_opt_');"><s:message code="edit"/></button>
						</shiro:hasPermission>
					</div>
					<div class="btn-group">
						<shiro:hasPermission name="core:message:delete">
						<button class="btn btn-default" type="button" onclick="return optDelete(this.form);"><s:message code="delete"/></button>
						</shiro:hasPermission>
					</div>
				</div>
				<table id="pagedTable" class="table table-condensed table-bordered table-hover ls-tb form-inline">
				  <thead id="sortHead" pagesort="<c:out value='${page_sort[0]}' />" pagedir="${page_sort_dir[0]}" pageurl="list.do?page_sort={0}&page_sort_dir={1}&${searchstringnosort}">
				  <tr class="ls_table_th">
				    <th width="25"><input type="checkbox" onclick="Cms.check('ids',this.checked);"/></th>
				    <th width="90"><s:message code="operate"/></th>
				    <th width="30" class="ls-th-sort"><span class="ls-sort" pagesort="id">ID</span></th>
				    <th width="110" class="ls-th-sort"><span class="ls-sort" pagesort="sender.username"><s:message code="message.sender"/></span></th>
				    <th width="110" class="ls-th-sort"><span class="ls-sort" pagesort="receiver.username"><s:message code="message.receiver"/></span></th>
				    <th width="160" class="ls-th-sort"><span class="ls-sort" pagesort="sendTime"><s:message code="message.sendTime"/></span></th>
				    <th><s:message code="message.content"/></th>
				    <th width="100" class="ls-th-sort"><span class="ls-sort" pagesort="deletionFlag"><s:message code="message.deletionFlag"/></span></th>
				    <th width="100" class="ls-th-sort"><span class="ls-sort" pagesort="unread"><s:message code="message.unread"/></span></th>
				  </tr>
				  </thead>
				  <tbody>
				  <c:forEach var="bean" varStatus="status" items="${pagedList.content}">
				  <tr beanid="${bean.id}">
				    <td><input type="checkbox" name="ids" value="${bean.id}"/></td>
				    <td align="center">
				    	<shiro:hasPermission name="core:message:edit">
				      <a id="edit_opt_${bean.id}" href="edit.do?id=${bean.id}&position=${pagedList.number*pagedList.size+status.index}&${searchstring}" class="ls-opt"><s:message code="edit"/></a>
				      </shiro:hasPermission>
				    	<shiro:hasPermission name="core:message:delete">
				      <a href="delete.do?ids=${bean.id}&${searchstring}" onclick="return confirmDelete();" class="ls-opt"><s:message code="delete"/></a>
				      </shiro:hasPermission>
				     </td>
				    <td><c:out value="${bean.id}"/></td>
				    <td><c:out value="${bean.sender.username}"/></td>
				    <td><c:out value="${bean.receiver.username}"/></td>
				    <td align="center"><fmt:formatDate value="${bean.sendTime}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
				    <td>
				    	<div><strong><c:out value="${fnx:substringx_sis(bean.subject,50,'...')}"/></strong></div>
				    	<div><c:out value="${fnx:substringx_sis(bean.text,50,'...')}"/></div>
				    </td>
				    <td><s:message code="message.deletionFlag.${bean.deletionFlag}"/></td>
				    <td><c:choose><c:when test="${bean.unread}"><strong><s:message code="yes"/></strong></c:when><c:otherwise><s:message code="no"/></c:otherwise></c:choose></td>
				  </tr>
				  </c:forEach>
				  </tbody>
				</table>
				<c:if test="${fn:length(pagedList.content) le 0}"> 
				<div class="ls-norecord"><s:message code="recordNotFound"/></div>
				</c:if>
			</form>
			<form action="list.do" method="get" class="ls-page">
				<tags:search_params excludePage="true"/>
			  <tags:pagination pagedList="${pagedList}"/>
			</form>
		</div>
	</div>
</div>
</body>
</html>