src/main/java/com/jspxcms/core/domain/Node.java
package com.jspxcms.core.domain;

import com.google.common.base.Objects;
import com.jspxcms.common.util.Reflections;
import com.jspxcms.common.web.Anchor;
import com.jspxcms.common.web.ImageAnchor;
import com.jspxcms.common.web.ImageAnchorBean;
import com.jspxcms.common.web.PageUrlResolver;
import com.jspxcms.core.constant.Constants;
import com.jspxcms.core.domain.NodeOrg.NodeOrgComparator;
import com.jspxcms.core.support.Context;
import com.jspxcms.core.support.Siteable;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.math.NumberUtils;
import org.hibernate.annotations.MapKeyType;
import org.hibernate.annotations.SortComparator;
import org.hibernate.annotations.Type;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlTransient;
import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.*;

import static com.jspxcms.core.constant.Constants.DYNAMIC_SUFFIX;
import static com.jspxcms.core.constant.Constants.SITE_PREFIX;

/**
 * Node
 *
 * @author liufang
 */
@Entity
@Table(name = "cms_node")
public class Node implements java.io.Serializable, Anchor, Siteable, PageUrlResolver {
    private static final long serialVersionUID = 1L;
    /**
     * 首页模型类型
     */
    public static final String HOME_MODEL_TYPE = "node_home";
    /**
     * 节点模型类型
     */
    public static final String NODE_MODEL_TYPE = "node";
    /**
     * 附件类型
     */
    public static final String ATTACH_TYPE = "node";
    /**
     * 手动生成
     */
    public static final int STATIC_MANUAL = 0;
    /**
     * 自动生成信息页
     */
    public static final int STATIC_INFO = 1;
    /**
     * 自动生成信息页、节点页
     */
    public static final int STATIC_INFO_NODE = 2;
    /**
     * 自动生成信息页、节点页、父节点页、首页
     */
    public static final int STATIC_INFO_NODE_PARENT = 3;
    /**
     * 自动生成信息页、节点页、父节点页、首页、列表页
     */
    public static final int STATIC_INFO_NODE_PARENT_LIST = 4;

    /**
     * 未开启
     */
    public static final String HTML_DISABLED = "0";
    /**
     * 待发布
     */
    public static final String HTML_TOBE_PUBLISH = "1";
    /**
     * 待生成
     */
    public static final String HTML_TOBE_GENERATE = "2";
    /**
     * 待更新
     */
    public static final String HTML_TOBE_UPDATE = "3";
    /**
     * 待删除
     */
    public static final String HTML_TOBE_DELETE = "4";
    /**
     * 已生成
     */
    public static final String HTML_GENERATED = "5";

    /**
     * 树编码长度
     */
    public static int TREE_NUMBER_LENGTH = 4;
    /**
     * 替换标识:节点ID
     */
    public static String PATH_NODE_ID = "{node_id}";
    /**
     * 替换标识:节点编码
     */
    public static String PATH_NODE_NUMBER = "{node_number}";

    /**
     * 节点正文KEY
     */
    public static String NODE_TEXT = "text";

    public static final String COVER_TEMPLATE = "coverTemplate";
    public static final String LIST_TEMPLATE = "listTemplate";
    public static final String TEMPLATE = "template";
    public static final String GENERATE_NODE = "generateNode";
    public static final String GENERATE_INFO = "generateInfo";
    public static final String NODE_PATH = "nodePath";
    public static final String INFO_PATH = "infoPath";
    public static final String NODE_EXTENSION = "nodeExtension";
    public static final String INFO_EXTENSION = "infoExtension";
    public static final String DEF_PAGE = "defPage";
    public static final String STATIC_METHOD = "staticMethod";
    public static final String STATIC_PAGE = "staticPage";

    public static String getCoverTemplate(Map<String, String> customs) {
        return customs != null ? customs.get(COVER_TEMPLATE) : null;
    }

    public static String getListTemplate(Map<String, String> customs) {
        return customs != null ? customs.get(LIST_TEMPLATE) : null;
    }

    public static String getTemplate(Map<String, String> customs) {
        return customs != null ? customs.get(TEMPLATE) : null;
    }

    public static boolean getGenerateNode(Map<String, String> customs) {
        String value = customs != null ? customs.get(GENERATE_NODE) : null;
        return value != null ? Boolean.valueOf(value) : false;
    }

    public static boolean getGenerateInfo(Map<String, String> customs) {
        String value = customs != null ? customs.get(GENERATE_INFO) : null;
        return value != null ? Boolean.valueOf(value) : false;
    }

    public static String getNodePath(Map<String, String> customs) {
        return customs != null ? customs.get(NODE_PATH) : null;
    }

    public static String getInfoPath(Map<String, String> customs) {
        return customs != null ? customs.get(INFO_PATH) : null;
    }

    public static String getNodeExtension(Map<String, String> customs) {
        return customs != null ? customs.get(NODE_EXTENSION) : null;
    }

    public static String getInfoExtension(Map<String, String> customs) {
        return customs != null ? customs.get(INFO_EXTENSION) : null;
    }

    public static boolean getDefPage(Map<String, String> customs) {
        String value = customs != null ? customs.get(DEF_PAGE) : null;
        return value != null ? Boolean.valueOf(value) : false;
    }

    public static int getStaticMethod(Map<String, String> customs) {
        String value = customs != null ? customs.get(STATIC_METHOD) : null;
        return NumberUtils.toInt(value, Node.STATIC_INFO_NODE_PARENT_LIST);
    }

    public static int getStaticPage(Map<String, String> customs) {
        String value = customs != null ? customs.get(STATIC_PAGE) : null;
        return NumberUtils.toInt(value, 1);
    }

    @Transient
    public boolean isViewPerm(Collection<MemberGroup> groups, Collection<Org> orgs) {
        if (Reflections.containsAny(getViewGroups(), groups, "id")) {
            return true;
        }
        if (CollectionUtils.isNotEmpty(orgs) && Reflections.containsAny(getViewOrgs(), orgs, "id")) {
            return true;
        }
        return false;
    }

    @Transient
    public boolean isDataPerm(User user) {
        Integer siteId = getSite().getId();
        if (user.getAllNodePerm(siteId) || Reflections.contains(user.getNodePerms(siteId), getId(), "id")) {
            return true;
        }
        return false;
    }

    @Transient
    public boolean isContriPerm(User user, Collection<MemberGroup> groups) {
        if (!getRealNode()) {
            // 不是真实节点（没有信息的节点）不允许投稿
            return false;
        }
        Set<MemberGroup> contriGroups = getContriGroups();
        return Reflections.containsAny(contriGroups, groups, "id");
    }

    @Transient
    public void updateHtmlStatus() {
        Node node = this;
        while (node != null) {
            if (node.getGenerate()) {
                if (StringUtils.isBlank(node.getHtml())) {
                    node.setHtmlStatus(HTML_TOBE_GENERATE);
                } else {
                    node.setHtmlStatus(HTML_GENERATED);
                }
            } else {
                if (StringUtils.isNotBlank(node.getHtml())) {
                    node.setHtmlStatus(HTML_TOBE_DELETE);
                } else {
                    node.setHtmlStatus(HTML_DISABLED);
                }
            }
            node = node.getParent();
        }
    }

    @Transient
    public String getUrl() {
        return getUrl(1);
    }

    @Transient
    public String getUrlMobile() {
        boolean isFull = getSite().getIdentifyDomain();
        return getUrlMobile(isFull);
    }

    @Transient
    public String getUrlMobile(boolean isFull) {
        return getGenerate() ? getUrlStatic(1, isFull, false, true) : getUrlDynamic(1, isFull, true);
    }

    @Transient
    public String getUrl(Integer page) {
        return getGenerate() ? getUrlStatic(page) : getUrlDynamic(page);
    }

    @Transient
    public String getUrlDynamic() {
        return getUrlDynamic(1);
    }

    @Transient
    public String getUrlDynamicFull() {
        return getUrlDynamicFull(1);
    }

    @Transient
    public String getUrlDynamicFull(Integer page) {
        return getUrlDynamic(page, true, Context.isMobile());
    }

    @Transient
    public String getUrlDynamic(Integer page) {
        Site site = getSite();
        boolean isFull = site.getIdentifyDomain();
        return getUrlDynamic(page, isFull, Context.isMobile());
    }

	@Transient
	public String getUrlDynamic(Integer page, boolean isFull, boolean isMobile) {
		if (isLinked()) {
			return getLinkUrl();
		}
		Site site = getSite();
		StringBuilder sb = new StringBuilder();
		if (isFull) {
			String domain = isMobile && StringUtils.isNotBlank(site.getMobileDomain()) ? site.getMobileDomain() : site.getDomain();
			sb.append(site.getProtocol()).append("://").append(domain);
			if (site.getPort() != null) {
				sb.append(":").append(site.getPort());
			}
		}
		String ctx = getSite().getContextPath();
		if (StringUtils.isNotBlank(ctx)) {
			sb.append(ctx);
		}
		boolean sitePrefix = !site.getIdentifyDomain() && !site.isDef();
		if (sitePrefix) {
			sb.append(SITE_PREFIX).append(site.getNumber());
		}
		sb.append("/");
		if (getParent() != null) {
			sb.append(Constants.NODE_PATH).append("/").append(getId());
			if (page != null && page > 1) {
				sb.append("_").append(page);
			}
			sb.append(DYNAMIC_SUFFIX);
		} else {
			if (sitePrefix) {
				sb.append(DYNAMIC_SUFFIX);
			} else {
				// 首页直接使用根路径
			}
		}
		return sb.toString();
	}

    @Transient
    public String getUrlStatic() {
        return getUrlStatic(1);
    }

    @Transient
    public String getUrlStatic(Integer page) {
        Site site = getSite();
        boolean isFull = site.getIdentifyDomain();

src/main/java/com/jspxcms/core/web/back/LoginController.java
package com.jspxcms.core.web.back;

import static org.apache.shiro.web.filter.authc.FormAuthenticationFilter.DEFAULT_ERROR_KEY_ATTRIBUTE_NAME;
import static org.apache.shiro.web.filter.authc.FormAuthenticationFilter.DEFAULT_USERNAME_PARAM;

import javax.servlet.http.HttpServletRequest;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

/**
 * LoginController
 * 
 * @author liufang
 * 
 */
@Controller
public class LoginController {
	@GetMapping(value = "/login.do")
	public String login() {
		return "login";
	}

	@PostMapping(value = "/login.do")
	public String fail(@RequestParam(DEFAULT_USERNAME_PARAM) String username,
			HttpServletRequest request, RedirectAttributes redirect) {
		Object errorName = request
				.getAttribute(DEFAULT_ERROR_KEY_ATTRIBUTE_NAME);
		if (errorName != null) {
			redirect.addFlashAttribute(DEFAULT_ERROR_KEY_ATTRIBUTE_NAME,
					errorName);
		}
		redirect.addFlashAttribute("username", username);
		return "redirect:login.do";
	}

	// @RequestMapping("/login.do")
	// public String login(String username, String password,
	// HttpServletRequest request, RedirectAttributes redirect) {
	// String result = "redirect:index.do";
	// if (StringUtils.isBlank(username)) {
	// return result;
	// }
	// User user = userService.findByUsername(username);
	// String message = null;
	// if (user != null) {
	// if (passwordEncoder.isPasswordValid(user.getPassword(), password,
	// user.getSaltBytes())) {
	// String loginIp = Servlets.getIpAddr(request);
	// userService.updateLoginIp(user.getId(), loginIp);
	// CmsContext.setUserId(request.getSession(), user.getId());
	// } else {
	// message = WRONG_PASSWORD;
	// }
	// } else {
	// message = USERNAME_NOT_EXIST;
	// }
	// if (StringUtils.isNotBlank(message)) {
	// redirect.addFlashAttribute(MESSAGE, message);
	// }
	// return result;
	// }

}

src/main/java/com/jspxcms/core/web/fore/LoginController.java
package com.jspxcms.core.web.fore;

import static com.jspxcms.core.security.CmsAuthenticationFilter.FALLBACK_URL_PARAM;
import static org.apache.shiro.web.filter.authc.FormAuthenticationFilter.DEFAULT_ERROR_KEY_ATTRIBUTE_NAME;
import static org.apache.shiro.web.filter.authc.FormAuthenticationFilter.DEFAULT_USERNAME_PARAM;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import com.jspxcms.common.web.Servlets;
import com.jspxcms.core.constant.Constants;
import com.jspxcms.core.domain.Site;
import com.jspxcms.core.support.Context;
import com.jspxcms.core.support.ForeContext;

/**
 * LoginController
 *
 * @author liufang
 */
@Controller
public class LoginController {
    public static final String LOGIN_URL = "/login";
    public static final String LOGIN_TEMPLATE = "sys_member_login.html";
    public static final String LOGIN_INCLUDE_TEMPLATE = "sys_member_login_include.html";
    public static final String LOGIN_AJAX_TEMPLATE = "sys_member_login_ajax.html";

    @GetMapping(value = {LOGIN_URL, Constants.SITE_PREFIX_PATH + "" + LOGIN_URL})
    public String login(String fallbackUrl, HttpServletRequest request, org.springframework.ui.Model modelMap) {
        Site site = Context.getCurrentSite();
        Map<String, Object> data = modelMap.asMap();
        ForeContext.setData(data, request);
        modelMap.addAttribute(FALLBACK_URL_PARAM, fallbackUrl);
        return site.getTemplate(LOGIN_TEMPLATE);
    }

    @GetMapping(value = {"/login_include", Constants.SITE_PREFIX_PATH + "/login_include"})
    public String loginInclude(String fallbackUrl, HttpServletRequest request, HttpServletResponse response, org.springframework.ui.Model modelMap) {
        Site site = Context.getCurrentSite();
        Map<String, Object> data = modelMap.asMap();
        ForeContext.setData(data, request);
        Servlets.setNoCacheHeader(response);
        modelMap.addAttribute(FALLBACK_URL_PARAM, fallbackUrl);
        return site.getTemplate(LOGIN_INCLUDE_TEMPLATE);
    }

    @GetMapping(value = {"/login_ajax", Constants.SITE_PREFIX_PATH + "/login_ajax"})
    public String loginAjax(String fallbackUrl, HttpServletRequest request, HttpServletResponse response, org.springframework.ui.Model modelMap) {
        Site site = Context.getCurrentSite();
        Map<String, Object> data = modelMap.asMap();
        ForeContext.setData(data, request);
        Servlets.setNoCacheHeader(response);
        modelMap.addAttribute(FALLBACK_URL_PARAM, fallbackUrl);
        return site.getTemplate(LOGIN_AJAX_TEMPLATE);
    }

    @PostMapping(value = {"/login", Constants.SITE_PREFIX_PATH + "/login"})
    public String loginFail(@RequestParam(DEFAULT_USERNAME_PARAM) String username, String fallbackUrl, HttpServletRequest request, RedirectAttributes ra) {
        Object errorName = request.getAttribute(DEFAULT_ERROR_KEY_ATTRIBUTE_NAME);
        if (errorName != null) {
            ra.addFlashAttribute(DEFAULT_ERROR_KEY_ATTRIBUTE_NAME, errorName);
        }
        ra.addFlashAttribute(DEFAULT_USERNAME_PARAM, username);
        ra.addAttribute(FALLBACK_URL_PARAM, fallbackUrl);
        return "redirect:login";
    }
}

src/main/webapp/WEB-INF/views/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="fnx" uri="http://java.sun.com/jsp/jstl/functionsx"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="f" uri="http://www.jspxcms.com/tags/form"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="shiro" uri="http://shiro.apache.org/tags" %>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><jsp:include page="/WEB-INF/views/title.jsp"/></title>
  <meta name="renderer" content="webkit">
  <!-- <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"> -->
  <script>if(top!=this){top.location=this.location;}</script>
  <link rel="stylesheet" href="${ctx}/static/vendor/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="${ctx}/static/vendor/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="${ctx}/static/vendor/ionicons/css/ionicons.min.css">
  <link rel="stylesheet" href="${ctx}/static/vendor/adminlte/css/AdminLTE.min.css">
  <link rel="stylesheet" href="${ctx}/static/vendor/adminlte/css/skins/skin-blue.min.css">
  <link rel="stylesheet" href="${ctx}/static/css/main.css">
  <!--[if lt IE 9]>
  <script src="${ctx}/static/vendor/html5shiv/html5shiv.min.js"></script>
  <script src="${ctx}/static/vendor/respond/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!--  style="overflow:visible;" -->
<div class="wrapper" style="overflow:visible;">
  <header class="main-header">
    <!-- Logo -->
    <a href="index.do" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b></b>CMS</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>jspX</b>CMS</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
        	<li style="padding:10px 5px 0 ;">
			      <select class="form-control input-sm" onchange="location.href='index.do?_site='+$(this).val();" style="border-radius:4px;background-color:#ecf0f5;">
						  <c:forEach var="s" items="${siteList}">
						  	<option value="${s.id}"<c:if test="${site.id==s.id}"> selected="selected"</c:if>>${s.name}(${s.org.name})</option>
						  </c:forEach>
			      </select> 
      		</li>
        	<li>
			      <a href="${site.url}" target="_blank" title="网站首页">
			        <i class="glyphicon glyphicon-home"></i>
			      </a>
      		</li>
        	<li>
            <a href="core/homepage/notification_list.do" target="center" title="我的通知">
              <i class="fa fa-bell-o"></i>
              <span id="notificationCount" class="label label-warning"></span>
            </a>
        	</li>
        	<li class="user-menu">
            <a href="javascript:;">
              <!-- The user image in the navbar-->
              <img src="${ctx}/static/img/anonymous.png" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">${user.username}</span>
            </a>
          </li>
        	<li>
            <a href="logout.do" title="退出">
              <span>退出</span> <i class="glyphicon glyphicon-log-out"></i>
            </a>
        	</li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <!-- <li class="header">功能导航</li> -->
        <c:forEach var="menu" varStatus="status" items="${menus}">
        	<shiro:hasPermission name="${menu.perm}">
	        <c:choose>
	        	<c:when test="${fn:length(menu.children)>0}">
			        <li class="treeview<c:if test="${status.index==0}"> active</c:if>">
			          <a href='javascript:;'><i class="${empty menu.icon ? 'fa fa-circle-o' : menu.icon}"></i> <span><s:message code="${menu.name}" text="${menu.name}"/></span>
			            <span class="pull-right-container">
			              <i class="fa fa-angle-left pull-right"></i>
			            </span>
			          </a>
			          <ul class="treeview-menu">
        					<c:forEach var="m" varStatus="status" items="${menu.children}">
        						<shiro:hasPermission name="${m.perm}">
        						<c:choose>
        						<c:when test="${fn:length(m.children)>0}">
        							<li class="treeview">
							          <a href='javascript:;'><i class="${empty m.icon ? 'fa fa-circle-o' : m.icon}"></i> <span><s:message code="${m.name}" text="${m.name}"/></span>
							            <span class="pull-right-container">
							              <i class="fa fa-angle-left pull-right"></i>
							            </span>
							          </a>
							          <ul class="treeview-menu">
							          	<c:forEach var="c" varStatus="status" items="${m.children}">
							          		<shiro:hasPermission name="${c.perm}">
							          		<li><a href="javascript:nav('${c.centerUrl}','${c.leftUrl}');"><i class="${empty c.icon ? 'fa fa-circle-o' : c.icon}"></i> <span><s:message code="${c.name}" text="${c.name}"/></span></a></li>
							          		</shiro:hasPermission>
							          	</c:forEach>
							          </ul>
							        </li>
        						</c:when>
        						<c:otherwise>
        							<c:choose>
        								<c:when test="${fn:startsWith(m.perm,'core:user_global:') || fn:startsWith(m.perm,'core:org_global:') || fn:startsWith(m.perm,'core:site:') || fn:startsWith(m.perm,'core:conf_global:') || fn:startsWith(m.perm,'core:publish_point:')}">
        								<shiro:hasRole name="super">
        									<li><a href="javascript:nav('${m.centerUrl}','${m.leftUrl}');"><i class="${empty m.icon ? 'fa fa-circle-o' : m.icon}"></i> <span><s:message code="${m.name}" text="${m.name}"/></span></a></li>
        								</shiro:hasRole>
        								</c:when>
        								<c:otherwise>
        									<li><a href="javascript:nav('${m.centerUrl}','${m.leftUrl}');"><i class="${empty m.icon ? 'fa fa-circle-o' : m.icon}"></i> <span><s:message code="${m.name}" text="${m.name}"/></span></a></li>
        								</c:otherwise>
        							</c:choose>		        					
        						</c:otherwise>
        						</c:choose>
        						</shiro:hasPermission>
			            </c:forEach>
			          </ul>
			        </li>
	        	</c:when>
	        	<c:otherwise>
			        <li><a href="javascript:nav('${menu.centerUrl}','${menu.leftUrl}');"><i class="${empty menu.icon ? 'fa fa-circle-o' : menu.icon}"></i> <span><s:message code="${menu.name}" text="${menu.name}"/></span></a></li>
	        	</c:otherwise>
	        </c:choose>
	        </shiro:hasPermission>
        </c:forEach>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper clearfix">
  	<div id="leftContentWrapper" class="pull-left" style="width:0;position:relative;">
    	<iframe class="" id="leftFrame" name="left" style="width:100%;min-height:100%;border:0;" src="blank.do"></iframe>
  	</div>
  	<div id="centerContentWrapper" class="" style="margin-left:0;position:relative;">
    	<iframe class="" id="centerFrame" name="center" scrolling="no" style="width:100%;min-height:100%;border:0;" src="core/homepage/welcome.do"></iframe>
  	</div>
  </div>
  <!-- /.content-wrapper -->

</div>
<!-- ./wrapper -->

<script src="${ctx}/static/vendor/jquery/jquery.min.js"></script>
<script src="${ctx}/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="${ctx}/static/vendor/adminlte/js/app.min.js"></script>
<script>
$(function() {
	var getNotificationCount = function() {
		$.get("core/notification/count.do",function(count) {
			if(count && parseInt(count)>0) {
				$("#notificationCount").text(count);
			} else {
				$("#notificationCount").text("");
			}		
		});
	}
	getNotificationCount();
	setInterval(getNotificationCount,120000);
	
	$(".treeview-menu>li:not(.treeview)>a").click(function() {
		$(this).parent().parent().find("li").removeClass("active");
		$(this).parent().parent().parent().parent().find("li").not($(this).parent().parent().parent()[0]).removeClass("active");
		$(this).parent().addClass("active");
	});
});
//var leftFrame = window.frames['left'];
//var centerFrame = window.frames['center'];
function nav(centerUrl,leftUrl) {
	//先移除内容，以免调整框架宽度时页面晃动
	try{$(window.frames['center'].document.body).empty();}catch(ex){}
	
	if(leftUrl) {
		//$(window.frames['leftFrame'].document.body).empty();
		if($("#leftContentWrapper").css("width")!="220px") {		
			$("#leftContentWrapper").css("width","220px");
			$("#centerContentWrapper").css("margin-left","220px");	
		}
		window.frames['left'].location.href = leftUrl;
	} else {
		if($("#leftContentWrapper").css("width")!="0px") {
			$("#leftContentWrapper").css("width","0px");
			$("#centerContentWrapper").css("margin-left","0px");
			window.frames['left'].location.href = "blank.do";
		}
	}
	window.frames['center'].location.href = centerUrl;
}
$(function() {
	function contentResize() {
		var minHeight = $(".content-wrapper").css("min-height");
		$("#leftContentWrapper").css("min-height",minHeight);
		$("#centerContentWrapper").css("min-height",minHeight);
	}	
	contentResize();
	$(window).resize(function () {
		contentResize();
	});
	var centerFrame = document.getElementById("centerFrame");
	var leftFrame = document.getElementById("leftFrame");
	var frameHeightInterval = setInterval(function() {
		try{
			var centerHeight = $(window.frames['center'].document.body).height();
			var leftHeight = $(window.frames['left'].document.body).height();
			var minHeight = parseInt($(".content-wrapper").css("min-height")) - 5;
			var height = centerHeight > leftHeight ? centerHeight : leftHeight;
			height = height > minHeight ? height : minHeight;
			centerFrame.height = height;
			leftFrame.height = height;		
		} catch(ex) {
			//clearInterval(frameHeightInterval);
		}
	},200);
})
function keepSession() {
	$.get("${ctx}/keep_session?d="+new Date()*1);
}
setInterval(keepSession,600000);
</script>
</body>
</html>