src/main/java/com/jspxcms/core/domain/Message.java
package com.jspxcms.core.domain;

import static com.jspxcms.core.constant.Constants.DYNAMIC_SUFFIX;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;

import com.google.common.base.Objects;
import com.jspxcms.core.constant.Constants;

/**
 * The persistent class for the cms_message database table.
 * 
 */
@Entity
@Table(name = "cms_message")
public class Message implements Serializable {
	private static final long serialVersionUID = 1L;
	/**
	 * 通知类型
	 */
	public static final String NOTIFICATION_TYPE = "CMS_MESSAGE";
	/**
	 * 删除标志：未删除
	 */
	public static final int DELETION_NO = 0;
	/**
	 * 删除标志：发件人删除
	 */
	public static final int DELETION_SEND = 1;
	/**
	 * 删除标志：收件人删除
	 */
	public static final int DELETION_RECEIVE = 2;

	@Transient
	public String getUrl() {
		return getUrl(false, false);
	}

	@Transient
	public String getFullUrl() {
		return getUrl(true, false);
	}

	@Transient
	public String getBackendUrl() {
		return getUrl(false, true);
	}

	@Transient
	public String getBackendFullUrl() {
		return getUrl(true, true);
	}

	@Transient
	public String getUrl(boolean isFull, boolean isBackend) {
		Site site = getReceiver().getGlobal().getSite();
		StringBuilder sb = new StringBuilder();
		if (isFull) {
			sb.append(site.getProtocol()).append("://").append(site.getDomain());
			if (site.getPort() != null) {
				sb.append(":").append(site.getPort());
			}
		}
		String ctx = site.getContextPath();
		if (StringUtils.isNotBlank(ctx)) {
			sb.append(ctx);
		}
		if (isBackend) {
			sb.append(Constants.CMSCP).append("/core/homepage/message_contact.do?contactId=").append(getSender().getId());
		} else {
			sb.append("/my/message/contact/").append(getSender().getId()).append(DYNAMIC_SUFFIX);
		}
		return sb.toString();
	}

	/**
	 * 获取标题。如果主题存在，则获取主题；如果主题不存在，则获取正文前150字符。
	 * 
	 * @return
	 */
	@Transient
	public String getTitle() {
		if (StringUtils.isNotBlank(getSubject())) {
			return getSubject();
		} else {
			return StringUtils.substring(getText(), 0, 150);
		}
	}

	@Transient
	public String getSubject() {
		MessageText messageText = getMessageText();
		return messageText != null ? messageText.getSubject() : null;
	}

	@Transient
	public String getText() {
		MessageText messageText = getMessageText();
		return messageText != null ? messageText.getText() : null;
	}

	@Transient
	public void applyDefaultValue() {
		if (getSendTime() == null) {
			setSendTime(new Timestamp(System.currentTimeMillis()));
		}
		if (getDeletionFlag() == null) {
			setDeletionFlag(DELETION_NO);
		}
		if (getUnread() == null) {
			setUnread(true);
		}
	}

	@Override
	public int hashCode() {
		return Objects.hashCode(id);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof Message)) {
			return false;
		}
		Message bean = (Message) o;
		return Objects.equal(id, bean.getId());
	}

	@Id
	@TableGenerator(name = "tg_cms_message", pkColumnValue = "cms_message", initialValue = 1, allocationSize = 10)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "tg_cms_message")
	@Column(name = "message_id_")
	private Integer id;

	@OneToOne(cascade = CascadeType.ALL, orphanRemoval = true, mappedBy = "message", fetch = FetchType.LAZY)
	private MessageText messageText;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_id_")
	private User sender;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "receiver_id_")
	private User receiver;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_time_", nullable = false)
	private Date sendTime;

	@Column(name = "deletion_flag_", nullable = false)
	private Integer deletionFlag;

	@Column(name = "is_unread_", nullable = false)
	private Boolean unread;

	public Message() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getSender() {
		return sender;
	}

	public void setSender(User sender) {
		this.sender = sender;
	}

	public User getReceiver() {
		return receiver;
	}

	public void setReceiver(User receiver) {
		this.receiver = receiver;
	}

	public MessageText getMessageText() {
		return this.messageText;
	}

	public void setMessageText(MessageText messageText) {
		this.messageText = messageText;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public Integer getDeletionFlag() {
		return this.deletionFlag;
	}

	public void setDeletionFlag(Integer deletionFlag) {
		this.deletionFlag = deletionFlag;
	}

	public Boolean getUnread() {
		return this.unread;
	}

	public void setUnread(Boolean unread) {
		this.unread = unread;
	}
}

src/main/java/com/jspxcms/ext/domain/Ad.java
package com.jspxcms.ext.domain;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;

import com.jspxcms.core.domain.Site;
import com.jspxcms.core.support.Siteable;

/**
 * Ad 广告
 * 
 * @author liufang
 * 
 */
@Entity
@Table(name = "cms_ad")
public class Ad implements Siteable, java.io.Serializable {
	private static final long serialVersionUID = 1L;
	/**
	 * 附件类型
	 */
	public static final String ATTACH_TYPE = "ad";

	@Transient
	public Set<String> getAttachUrls() {
		Set<String> attachUrls = new HashSet<String>();
		if (StringUtils.isNotBlank(getImage())) {
			attachUrls.add(getImage());
		}
		if (StringUtils.isNoneBlank(getFlash())) {
			attachUrls.add(getFlash());
		}
		return attachUrls;
	}

	@Transient
	public void applyDefaultValue() {
		if (getSeq() == null) {
			setSeq(50);
		}
	}

	private Integer id;
	private AdSlot slot;
	private Site site;

	private String name;
	private Date beginDate;
	private Date endDate;
	private String url;
	private String text;
	private String script;
	private String image;
	private String flash;
	private Integer seq;

	@Id
	@Column(name = "f_ad_id", unique = true, nullable = false)
	@TableGenerator(name = "tg_cms_ad", pkColumnValue = "cms_ad", initialValue = 1, allocationSize = 10)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "tg_cms_ad")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_adslot_id", nullable = false)
	public AdSlot getSlot() {
		return this.slot;
	}

	public void setSlot(AdSlot slot) {
		this.slot = slot;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@Column(name = "f_name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "f_begin_date", length = 19)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "f_end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "f_url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "f_text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "f_script")
	public String getScript() {
		return this.script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	@Column(name = "f_image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "f_flash")
	public String getFlash() {
		return this.flash;
	}

	public void setFlash(String flash) {
		this.flash = flash;
	}

	@Column(name = "f_seq")
	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}
}

src/main/java/com/jspxcms/ext/domain/AdSlot.java
package com.jspxcms.ext.domain;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;

import com.jspxcms.core.domain.Site;
import com.jspxcms.core.support.Siteable;

/**
 * 广告板位
 * 
 * @author liufang
 * 
 */
@Entity
@Table(name = "cms_ad_slot")
public class AdSlot implements Siteable, java.io.Serializable {
	private static final long serialVersionUID = 1L;
	public static final int TEXT = 1;
	public static final int IMAGE = 2;
	public static final int FLASH = 3;
	public static final int CODE = 4;

	@Transient
	public void addAd(Ad ad) {
		List<Ad> ads = getAds();
		if (ads == null) {
			ads = new ArrayList<Ad>();
			setAds(ads);
		}
		ads.add(ad);
	}

	@Transient
	public void removeAd(Ad ad) {
		List<Ad> ads = getAds();
		if (ads != null) {
			ads.remove(ad);
		}

	}

	@Transient
	public void applyDefaultValue() {
		if (getType() == null) {
			setType(TEXT);
		}
	}

	private Integer id;
	private List<Ad> ads = new ArrayList<Ad>(0);

	private Site site;

	private String name;
	private String number;
	private String description;
	private Integer type;
	private String template;
	private Integer width;
	private Integer height;

	@Id
	@Column(name = "f_adslot_id", unique = true, nullable = false)
	@TableGenerator(name = "tg_cms_ad_slot", pkColumnValue = "cms_ad_slot", initialValue = 1, allocationSize = 10)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "tg_cms_ad_slot")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slot")
	@OrderBy(value = "seq asc, id asc")
	public List<Ad> getAds() {
		return this.ads;
	}

	public void setAds(List<Ad> ads) {
		this.ads = ads;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@Column(name = "f_name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "f_number", nullable = false, length = 100)
	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "f_description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "f_type", nullable = false)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "f_template", nullable = false)
	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	@Column(name = "f_width", nullable = false)
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "f_height", nullable = false)
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}
}

src/main/java/com/jspxcms/ext/domain/Favorite.java
package com.jspxcms.ext.domain;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.jspxcms.common.web.Anchor;
import com.jspxcms.core.domain.User;

@Entity
@Table(name = "cms_favorite")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "dtype_", discriminatorType = DiscriminatorType.STRING)
public abstract class Favorite implements Serializable {
	private static final long serialVersionUID = 1L;

	@Transient
	public abstract Anchor getAnchor();

	@Transient
	public void applyDefaultValue() {
		if (getCreated() == null) {
			setCreated(new Timestamp(System.currentTimeMillis()));
		}
	}

	@Id
	@Column(name = "favorite_id_", unique = true, nullable = false)
	@TableGenerator(name = "cms_favorite", pkColumnValue = "cms_favorite", initialValue = 1, allocationSize = 10)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "cms_favorite")
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id_", nullable = false)
	private User user;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_")
	private Date created;

	public Favorite() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}
}

src/main/java/com/jspxcms/ext/domain/FriendlinkType.java
package com.jspxcms.ext.domain;

// Generated 2013-6-14 17:19:05 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.jspxcms.core.domain.Site;
import com.jspxcms.core.support.Siteable;

/**
 * FriendlinkType
 * 
 * @author yangxing
 * 
 */
@Entity
@Table(name = "cms_friendlink_type")
public class FriendlinkType implements Siteable, java.io.Serializable {
	private static final long serialVersionUID = 1L;

	public void applyDefaultValue() {
		if (getSeq() == null) {
			setSeq(Integer.MAX_VALUE);
		}
	}

	private Integer id;

	private Site site;

	private String name;
	private String number;
	private Integer seq;

	@Id
	@Column(name = "f_friendlinktype_id", unique = true, nullable = false)
	@TableGenerator(name = "tg_cms_friendlinktype", pkColumnValue = "cms_friendlinktype", initialValue = 1, allocationSize = 10)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "tg_cms_friendlinktype")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "f_site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@Column(name = "f_name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "f_number", length = 100)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "f_seq", nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

}

src/main/webapp/WEB-INF/views/ext/question_item/question_item_form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="fnx" uri="http://java.sun.com/jsp/jstl/functionsx"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="f" uri="http://www.jspxcms.com/tags/form"%>
<%@ taglib prefix="shiro" uri="http://shiro.apache.org/tags"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<!DOCTYPE html>
<html>
<head>
<jsp:include page="/WEB-INF/views/head.jsp"/>
<script type="text/javascript">
$(function() {
	$("#validForm").validate({
		submitHandler: function(form) {
		   $("#validForm input[name|='dy']").each(function() {
			   var name = $(this).attr("name");
			   $(this).attr("name",name.substring(3,name.lastIndexOf("-")));
		   });
		   form.submit();
		}
	});
	$("input[name='name']").focus();
	
});
function confirmDelete() {
	return confirm("<s:message code='confirmDelete'/>");
}
</script>
</head>
<body class="skin-blue content-body">
<jsp:include page="/WEB-INF/views/commons/show_message.jsp"/>
<div class="content-header">
	<h1><s:message code="questionItem.management"/> - <s:message code="${oprt=='edit' ? 'edit' : 'create'}"/></h1>
</div>
<div class="content">
	<div class="box box-primary">
		<form class="form-horizontal" id="validForm" action="${oprt=='edit' ? 'update' : 'save'}.do" method="post">
			<tags:search_params/>
			<f:hidden name="oid" value="${bean.id}"/>
			<f:hidden name="position" value="${position}"/>
			<input type="hidden" id="redirect" name="redirect" value="edit"/>
			<div class="box-header with-border">
				<div class="btn-toolbar">
					<div class="btn-group">
						<shiro:hasPermission name="ext:question:create">
						<button class="btn btn-default" type="button" value="" onclick="location.href='../question/edit.do?id=${question.id}';"><s:message code="return"/></button>
						</shiro:hasPermission>
					</div>
				</div>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-sm-12">
						<div class="form-group">
	            <label class="col-sm-2 control-label"><s:message code="questionItem.question"/></label>
	            <div class="col-sm-10">
	            	<p class="form-control-static"><c:out value="${question.title}"/></p>
	            </div>
	          </div>
	        </div>
	      </div>
	      
				<div class="row">
					<div class="col-sm-12">
						<div class="form-group">
	            <label class="col-sm-2 control-label"><em class="required">*</em><s:message code="questionItem.title"/></label>
	            <div class="col-sm-10">
	            	<f:text name="title" value="${oprt=='edit' ? (bean.title) : ''}" class="form-control required" maxlength="150"/>
	            </div>
	          </div>
	        </div>
	      </div>
	      
				<div class="row">
					<div class="col-sm-6">
						<div class="form-group">
	            <label class="col-sm-4 control-label"><s:message code="questionItem.multi"/></label>
	            <div class="col-sm-8">
	            	<label class="radio-inline"><f:radio name="maxSelected" value="0" checked="${bean.maxSelected}"/><s:message code="yes"/></label>
    						<label class="radio-inline"><f:radio name="maxSelected" value="1" checked="${bean.maxSelected}" default="1"/><s:message code="no"/></label>
	            </div>
	          </div>
	        </div>
					<div class="col-sm-6">
						<div class="form-group">
	            <label class="col-sm-4 control-label"><s:message code="questionItem.essay"/></label>
	            <div class="col-sm-8">
					    	<label class="radio-inline"><f:radio name="essay" value="true" checked="${bean.essay}"/><s:message code="yes"/></label>
					    	<label class="radio-inline"><f:radio name="essay" value="false" checked="${bean.essay}" default="false"/><s:message code="no"/></label>
	            </div>
	          </div>
	        </div>
	      </div>
				
				<div class="inls-opt">
				  <b><s:message code="questionItem.options"/></b> &nbsp;
				  <a href="javascript:;" onclick="addRow();" class="ls-opt"><s:message code='addRow'/></a> &nbsp;
				  <a href="javascript:;" onclick="Cms.moveTop('optionIds');" class="ls-opt"><s:message code='moveTop'/></a>
				  <a href="javascript:;" onclick="Cms.moveUp('optionIds');" class="ls-opt"><s:message code='moveUp'/></a>
				  <a href="javascript:;" onclick="Cms.moveDown('optionIds');" class="ls-opt"><s:message code='moveDown'/></a>
				  <a href="javascript:;" onclick="Cms.moveBottom('optionIds');" class="ls-opt"><s:message code='moveBottom'/></a>
				</div>
				<textarea id="templateArea" style="display:none">
					<tr>
				    <td align="center">
				    	<input type="checkbox" name="optionIds" value=""/>
				    	<input type="hidden" name="dy-optionId-{0}" value=""/>
				    </td>
				    <td align="center">    	
				      <a href="javascript:;" onclick="$(this).parent().parent().remove();" class="ls-opt"><s:message code="delete"/></a>
				    </td>
				    <td align="center"><f:text name="dy-optionTitle-{0}" value="" class="form-control required" maxlength="150"/></td>
				  </tr>
				</textarea>
				<script type="text/javascript">
				var rowIndex = 0;
				<c:if test="${!empty bean && fn:length(bean.options) gt 0}">
				rowIndex = ${fn:length(bean.options)};
				</c:if>
				var rowTemplate = $.format($("#templateArea").val());
				function addRow() {
					$(rowTemplate(rowIndex++)).appendTo("#pagedTable tbody");
					
				}
				$(function() {
					if(rowIndex==0) {
						<c:if test="${oprt=='create'}">
						addRow();
						</c:if>
					}
				});
				</script>
				<table id="pagedTable" class="table table-condensed table-bordered table-hover ls-tb">
				  <thead>
				  <tr>
				    <th width="25"><input type="checkbox" onclick="Cms.check('ids',this.checked);"/></th>
				    <th width="100"><s:message code="operate"/></th>
				    <th><s:message code="questionOption.title"/></th>
				  </tr>
				  </thead>
				  <tbody>
				  <c:forEach var="option" varStatus="status" items="${bean.options}">
				  <tr beanid="${option.id}">
				    <td align="center">
				    	<input type="checkbox" name="optionIds" value="${option.id}"/>
				    	<input type="hidden" name="dy-optionId-${status.index}" value="${option.id}"/>
				    </td>
				    <td align="center">
				      <a href="javascript:;" onclick="$(this).parent().parent().remove();" class="ls-opt"><s:message code="delete"/></a>
				    </td>
				    <td align="center"><f:text name="dy-optionTitle-${status.index}" value="${option.title}" class="form-control required" maxlength="150"/></td>
				  </tr>
				  </c:forEach>
				  </tbody>
				</table>
			</div>
			<div class="box-footer">
	      <button class="btn btn-primary" type="submit"><s:message code="save"/></button>
	      <button class="btn btn-default" type="submit" onclick="$('#redirect').val('list');"><s:message code="saveAndReturn"/></button>
	      <c:if test="${oprt=='create'}">
	      <button class="btn btn-default" type="submit" onclick="$('#redirect').val('create');"><s:message code="saveAndCreate"/></button>
     		</c:if>
			</div>
		</form>
	</div>
</div>
</body>
</html>